version: "3.7"
services:
  db:
    image: postgres:15
    container_name: app_db_fastapi
    environment:
      - POSTGRES_DB=project_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 1221
    expose:
      - 1221

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_api_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
