"""empty message

Revision ID: 2b5f2d5a6479
Revises: 6923e6200f48
Create Date: 2023-06-30 14:35:44.558699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5f2d5a6479'
down_revision = '6923e6200f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
