"""empty message

Revision ID: 6923e6200f48
Revises: 6180ff8a4db3
Create Date: 2023-06-30 13:05:01.991647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6923e6200f48'
down_revision = '6180ff8a4db3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done')
    # ### end Alembic commands ###
