"""all tables was added

Revision ID: 6b5663830cda
Revises: cd034dda8b24
Create Date: 2023-06-29 15:39:24.196213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5663830cda'
down_revision = 'cd034dda8b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
